# Word Representations and Text/Document similarity (count Based)

## Bag of Words

In [1]:
import pandas as pd
import numpy as np
import nltk
from nltk import word_tokenize

In [2]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to C:\Users\Shivani
[nltk_data]     Dussa\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [23]:
review_1 = 'The movie was good and we really like it'
review_2 = 'the movie was good but the ending was boring'
review_3 = 'We did not like the movie as it was too lenghty'

In [24]:
review_1_tokens = word_tokenize(review_1)
review_2_tokens = word_tokenize(review_2)
review_3_tokens = word_tokenize(review_3)

In [25]:
review_1_tokens

['The', 'movie', 'was', 'good', 'and', 'we', 'really', 'like', 'it']

In [26]:
review_2_tokens

['the', 'movie', 'was', 'good', 'but', 'the', 'ending', 'was', 'boring']

In [16]:
review_3_tokens

['We',
 'did',
 'not',
 'like',
 'the',
 'movie',
 'as',
 'it',
 'was',
 'too',
 'lenghty']

In [27]:
#print(review_2_tokens)
print(set(review_2_tokens))

{'but', 'boring', 'movie', 'ending', 'good', 'the', 'was'}


In [21]:
print(set(review_1_tokens))

{'movie', 'it', 'really', 'The', 'we', 'good', 'and', 'like', 'was'}


In [29]:
review_tokens = set(review_1_tokens).union(set(review_2_tokens)).union(set(review_3_tokens))
print(len(review_tokens))
print(review_tokens)

19
{'as', 'but', 'lenghty', 'boring', 'movie', 'really', 'ending', 'too', 'good', 'We', 'did', 'not', 'it', 'The', 'we', 'the', 'and', 'like', 'was'}


In [31]:
review1_dict = dict.fromkeys(review_tokens,0)
review2_dict = dict.fromkeys(review_tokens,0)
review3_dict = dict.fromkeys(review_tokens,0)
print(review1_dict)
print(review2_dict)
print(review3_dict)

{'as': 0, 'but': 0, 'lenghty': 0, 'boring': 0, 'movie': 0, 'really': 0, 'ending': 0, 'too': 0, 'good': 0, 'We': 0, 'did': 0, 'not': 0, 'it': 0, 'The': 0, 'we': 0, 'the': 0, 'and': 0, 'like': 0, 'was': 0}
{'as': 0, 'but': 0, 'lenghty': 0, 'boring': 0, 'movie': 0, 'really': 0, 'ending': 0, 'too': 0, 'good': 0, 'We': 0, 'did': 0, 'not': 0, 'it': 0, 'The': 0, 'we': 0, 'the': 0, 'and': 0, 'like': 0, 'was': 0}
{'as': 0, 'but': 0, 'lenghty': 0, 'boring': 0, 'movie': 0, 'really': 0, 'ending': 0, 'too': 0, 'good': 0, 'We': 0, 'did': 0, 'not': 0, 'it': 0, 'The': 0, 'we': 0, 'the': 0, 'and': 0, 'like': 0, 'was': 0}


In [33]:
for token in review_1_tokens:
    review1_dict[token]+=1
for token in review_2_tokens:
    review2_dict[token]+=1
for token in review_3_tokens:
    review3_dict[token]+=1

In [36]:
print(review1_dict)
print(review2_dict)
print(review3_dict)

{'as': 0, 'but': 0, 'lenghty': 0, 'boring': 0, 'movie': 1, 'really': 1, 'ending': 0, 'too': 0, 'good': 1, 'We': 0, 'did': 0, 'not': 0, 'it': 1, 'The': 1, 'we': 1, 'the': 0, 'and': 1, 'like': 1, 'was': 1}
{'as': 0, 'but': 1, 'lenghty': 0, 'boring': 1, 'movie': 1, 'really': 0, 'ending': 1, 'too': 0, 'good': 1, 'We': 0, 'did': 0, 'not': 0, 'it': 0, 'The': 0, 'we': 0, 'the': 2, 'and': 0, 'like': 0, 'was': 2}
{'as': 1, 'but': 0, 'lenghty': 1, 'boring': 0, 'movie': 1, 'really': 0, 'ending': 0, 'too': 1, 'good': 0, 'We': 1, 'did': 1, 'not': 1, 'it': 1, 'The': 0, 'we': 0, 'the': 1, 'and': 0, 'like': 1, 'was': 1}


In [38]:
df_reviews_dict = pd.DataFrame([review1_dict,review2_dict,review3_dict]) 
df_reviews_dict

as  but  lenghty  boring  movie  really  ending  too  good  We  did  not  \
0   0    0        0       0      1       1       0    0     1   0    0    0   
1   0    1        0       1      1       0       1    0     1   0    0    0   
2   1    0        1       0      1       0       0    1     0   1    1    1   

   it  The  we  the  and  like  was  
0   1    1   1    0    1     1    1  
1   0    0   0    2    0     0    2  
2   1    0   0    1    0     1    1

**This is the Term Frequency Matrix(TFM) or Document Term Matrix(DTM)**

## Count Vectorizer 
- sklearn implementation of TFM creation using Bag of Words

In [39]:
from sklearn.feature_extraction.text import CountVectorizer

In [41]:
review_list = [review_1,review_2,review_3]
review_list

['The movie was good and we really like it',
 'the movie was good but the ending was boring',
 'We did not like the movie as it was too lenghty']

In [42]:
count_vector = CountVectorizer(stop_words = 'english')
tfm = count_vector.fit_transform(review_list)
col_names = count_vector.get_feature_names()

C:\Users\Shivani Dussa\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [45]:
col_name_out = count_vector.get_feature_names_out()

In [48]:
col_name_out

array(['boring', 'did', 'ending', 'good', 'lenghty', 'like', 'movie',
       'really'], dtype=object)

In [50]:
col_names

array(['boring', 'did', 'ending', 'good', 'lenghty', 'like', 'movie',
       'really'], dtype=object)

### CSR means Compressed Sparced Row, which is a row-wise sparse matrix 

In [52]:
print(type(tfm))
print(tfm.toarray())
print(col_names)

<class 'scipy.sparse.csr.csr_matrix'>
[[0 0 0 1 0 1 1 1]
 [1 0 1 1 0 0 1 0]
 [0 1 0 0 1 1 1 0]]
['boring' 'did' 'ending' 'good' 'lenghty' 'like' 'movie' 'really']


In [53]:
data = pd.DataFrame(tfm.toarray(),columns = col_names)
data

boring  did  ending  good  lenghty  like  movie  really
0       0    0       0     1        0     1      1       1
1       1    0       1     1        0     0      1       0
2       0    1       0     0        1     1      1       0

## TF-IDF

In [54]:
from sklearn.feature_extraction.text import TfidfVectorizer