# Word Representations and Text/Document similarity (count Based)

## Bag of Words

In [39]:
import pandas as pd
import numpy as np
import nltk
from nltk import word_tokenize

In [40]:
nltk.download('punkt');

[nltk_data] Downloading package punkt to C:\Users\Shivani
[nltk_data]     Dussa\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [41]:
review_1 = 'The movie was good and we really like it'
review_2 = 'the movie was good but the ending was boring'
review_3 = 'We did not like the movie as it was too lenghty'

In [42]:
review_1_tokens = word_tokenize(review_1)
review_2_tokens = word_tokenize(review_2)
review_3_tokens = word_tokenize(review_3)

In [43]:
review_1_tokens

['The', 'movie', 'was', 'good', 'and', 'we', 'really', 'like', 'it']

In [44]:
review_2_tokens

['the', 'movie', 'was', 'good', 'but', 'the', 'ending', 'was', 'boring']

In [45]:
review_3_tokens

['We',
 'did',
 'not',
 'like',
 'the',
 'movie',
 'as',
 'it',
 'was',
 'too',
 'lenghty']

In [46]:
#print(review_2_tokens)
print(set(review_2_tokens))

{'was', 'movie', 'boring', 'good', 'the', 'but', 'ending'}


In [47]:
print(set(review_1_tokens))

{'was', 'movie', 'it', 'like', 'The', 'and', 'really', 'good', 'we'}


In [48]:
review_tokens = set(review_1_tokens).union(set(review_2_tokens)).union(set(review_3_tokens))
print(len(review_tokens))
print(review_tokens)

19
{'was', 'movie', 'boring', 'like', 'did', 'We', 'The', 'and', 'really', 'it', 'too', 'not', 'as', 'good', 'the', 'we', 'but', 'lenghty', 'ending'}


In [49]:
review1_dict = dict.fromkeys(review_tokens,0)
review2_dict = dict.fromkeys(review_tokens,0)
review3_dict = dict.fromkeys(review_tokens,0)
print(review1_dict)
print(review2_dict)
print(review3_dict)

{'was': 0, 'movie': 0, 'boring': 0, 'like': 0, 'did': 0, 'We': 0, 'The': 0, 'and': 0, 'really': 0, 'it': 0, 'too': 0, 'not': 0, 'as': 0, 'good': 0, 'the': 0, 'we': 0, 'but': 0, 'lenghty': 0, 'ending': 0}
{'was': 0, 'movie': 0, 'boring': 0, 'like': 0, 'did': 0, 'We': 0, 'The': 0, 'and': 0, 'really': 0, 'it': 0, 'too': 0, 'not': 0, 'as': 0, 'good': 0, 'the': 0, 'we': 0, 'but': 0, 'lenghty': 0, 'ending': 0}
{'was': 0, 'movie': 0, 'boring': 0, 'like': 0, 'did': 0, 'We': 0, 'The': 0, 'and': 0, 'really': 0, 'it': 0, 'too': 0, 'not': 0, 'as': 0, 'good': 0, 'the': 0, 'we': 0, 'but': 0, 'lenghty': 0, 'ending': 0}


In [50]:
for token in review_1_tokens:
    review1_dict[token]+=1
for token in review_2_tokens:
    review2_dict[token]+=1
for token in review_3_tokens:
    review3_dict[token]+=1

In [51]:
print(review1_dict)
print(review2_dict)
print(review3_dict)

{'was': 1, 'movie': 1, 'boring': 0, 'like': 1, 'did': 0, 'We': 0, 'The': 1, 'and': 1, 'really': 1, 'it': 1, 'too': 0, 'not': 0, 'as': 0, 'good': 1, 'the': 0, 'we': 1, 'but': 0, 'lenghty': 0, 'ending': 0}
{'was': 2, 'movie': 1, 'boring': 1, 'like': 0, 'did': 0, 'We': 0, 'The': 0, 'and': 0, 'really': 0, 'it': 0, 'too': 0, 'not': 0, 'as': 0, 'good': 1, 'the': 2, 'we': 0, 'but': 1, 'lenghty': 0, 'ending': 1}
{'was': 1, 'movie': 1, 'boring': 0, 'like': 1, 'did': 1, 'We': 1, 'The': 0, 'and': 0, 'really': 0, 'it': 1, 'too': 1, 'not': 1, 'as': 1, 'good': 0, 'the': 1, 'we': 0, 'but': 0, 'lenghty': 1, 'ending': 0}


In [52]:
df_reviews_dict = pd.DataFrame([review1_dict,review2_dict,review3_dict]) 
df_reviews_dict

was  movie  boring  like  did  We  The  and  really  it  too  not  as  \
0    1      1       0     1    0   0    1    1       1   1    0    0   0   
1    2      1       1     0    0   0    0    0       0   0    0    0   0   
2    1      1       0     1    1   1    0    0       0   1    1    1   1   

   good  the  we  but  lenghty  ending  
0     1    0   1    0        0       0  
1     1    2   0    1        0       1  
2     0    1   0    0        1       0

**This is the Term Frequency Matrix(TFM) or Document Term Matrix(DTM)**

## Count Vectorizer 
- sklearn implementation of TFM creation using Bag of Words

In [53]:
from sklearn.feature_extraction.text import CountVectorizer

In [54]:
review_list = [review_1,review_2,review_3]
review_list

['The movie was good and we really like it',
 'the movie was good but the ending was boring',
 'We did not like the movie as it was too lenghty']

In [55]:
count_vector = CountVectorizer(stop_words = 'english')
tfm = count_vector.fit_transform(review_list)
col_names = count_vector.get_feature_names()

C:\Users\Shivani Dussa\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [56]:
col_name_out = count_vector.get_feature_names_out()

In [57]:
col_name_out

array(['boring', 'did', 'ending', 'good', 'lenghty', 'like', 'movie',
       'really'], dtype=object)

In [58]:
col_names

['boring', 'did', 'ending', 'good', 'lenghty', 'like', 'movie', 'really']

### CSR means Compressed Sparced Row, which is a row-wise sparse matrix 

In [59]:
print(type(tfm))
print(tfm.toarray())
print(col_names)

<class 'scipy.sparse.csr.csr_matrix'>
[[0 0 0 1 0 1 1 1]
 [1 0 1 1 0 0 1 0]
 [0 1 0 0 1 1 1 0]]
['boring', 'did', 'ending', 'good', 'lenghty', 'like', 'movie', 'really']


In [60]:
data = pd.DataFrame(tfm.toarray(),columns = col_names)
data                          

boring  did  ending  good  lenghty  like  movie  really
0       0    0       0     1        0     1      1       1
1       1    0       1     1        0     0      1       0
2       0    1       0     0        1     1      1       0

In [24]:
# this table tells us how many times the word is repeating in 0,1,2
# in 0, boring, did,ending,lenthy words are not there so 0 and good,like,movie,really is there for one time so 1
#like wise...
# how many times the word repeats it takes that number

In [23]:
review_list

['The movie was good and we really like it',
 'the movie was good but the ending was boring',
 'We did not like the movie as it was too lenghty']

## TF-IDF

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [6]:
tf_vec = TfidfVectorizer(min_df = 1,lowercase = True,stop_words = 'english')

In [7]:
tf_vec

TfidfVectorizer(stop_words='english')

In [22]:
review_list

['The movie was good and we really like it',
 'the movie was good but the ending was boring',
 'We did not like the movie as it was too lenghty']

In [25]:
tf_matrix = tf_vec.fit_transform(review_list)
tf_names = tf_vec.get_feature_names()
print(type(tf_matrix))
print(tf_matrix.shape)

<class 'scipy.sparse.csr.csr_matrix'>
(3, 8)


C:\Users\Shivani Dussa\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [29]:
print(tf_names)
print(tf_matrix.toarray())       #check the 'data' in bag of words  same liekwise                                # 

['boring', 'did', 'ending', 'good', 'lenghty', 'like', 'movie', 'really']
[[0.         0.         0.         0.4804584  0.         0.4804584
  0.37311881 0.63174505]
 [0.5844829  0.         0.5844829  0.44451431 0.         0.
  0.34520502 0.        ]
 [0.         0.5844829  0.         0.         0.5844829  0.44451431
  0.34520502 0.        ]]


In [27]:
tf_matrix      

<3x8 sparse matrix of type '<class 'numpy.float64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [30]:
tf_df = pd.DataFrame(tf_matrix.toarray(),columns = tf_names)

In [31]:
tf_df      

boring       did    ending      good   lenghty      like     movie  \
0  0.000000  0.000000  0.000000  0.480458  0.000000  0.480458  0.373119   
1  0.584483  0.000000  0.584483  0.444514  0.000000  0.000000  0.345205   
2  0.000000  0.584483  0.000000  0.000000  0.584483  0.444514  0.345205   

     really  
0  0.631745  
1  0.000000  
2  0.000000

In [32]:
# in index 0,in review1, boring,did,ending,lenthy are not there so 0 and good,like,movie,really are there so 1
# Like wise

In [61]:
data

boring  did  ending  good  lenghty  like  movie  really
0       0    0       0     1        0     1      1       1
1       1    0       1     1        0     0      1       0
2       0    1       0     0        1     1      1       0

In [62]:
tf_df

boring       did    ending      good   lenghty      like     movie  \
0  0.000000  0.000000  0.000000  0.480458  0.000000  0.480458  0.373119   
1  0.584483  0.000000  0.584483  0.444514  0.000000  0.000000  0.345205   
2  0.000000  0.584483  0.000000  0.000000  0.584483  0.444514  0.345205   

     really  
0  0.631745  
1  0.000000  
2  0.000000

## Document similarity estimation

In [1]:
doc0 = 'Natural Language Processing is the study of making a machine understand and generate languages like humans'
doc1 = 'Cricket is a sports played with a bat and a ball. It is not played in many countries'
doc2 = 'Languages are the cornerstone of human evolution. Making a machine study languages is not easy'
doc3 = 'Football is a sport played in almost all countries of the world. It is played by kicking a ball'

In [9]:
documents = [doc0,doc1,doc2,doc3]

In [10]:
documents

['Natural Language Processing is the study of making a machine understand and generate languages like humans',
 'Cricket is a sports played with a bat and a ball. It is not played in many countries',
 'Languages are the cornerstone of human evolution. Making a machine study languages is not easy',
 'Football is a sport played in almost all countries of the world. It is played by kicking a ball']

In [17]:
import pandas as pd

In [15]:
tf_vect_docs = TfidfVectorizer(min_df = 1,lowercase = True,stop_words = 'english')
tf_matrix_docs = tf_vect_docs.fit_transform(documents)

In [18]:
tf_colnames = tf_vect_docs.get_feature_names()
tf_df = pd.DataFrame(tf_matrix_docs.toarray(),columns = tf_colnames)

In [19]:
tf_vect_docs

TfidfVectorizer(stop_words='english')

In [20]:
tf_matrix_docs

<4x25 sparse matrix of type '<class 'numpy.float64'>'
	with 32 stored elements in Compressed Sparse Row format>

In [21]:
tf_colnames

['ball',
 'bat',
 'cornerstone',
 'countries',
 'cricket',
 'easy',
 'evolution',
 'football',
 'generate',
 'human',
 'humans',
 'kicking',
 'language',
 'languages',
 'like',
 'machine',
 'making',
 'natural',
 'played',
 'processing',
 'sport',
 'sports',
 'study',
 'understand',
 'world']

In [22]:
tf_df

ball       bat  cornerstone  countries   cricket     easy  evolution  \
0  0.00000  0.000000      0.00000    0.00000  0.000000  0.00000    0.00000   
1  0.30392  0.385484      0.00000    0.30392  0.385484  0.00000    0.00000   
2  0.00000  0.000000      0.34604    0.00000  0.000000  0.34604    0.34604   
3  0.28358  0.000000      0.00000    0.28358  0.000000  0.00000    0.00000   

   football  generate    human  ...   machine    making   natural    played  \
0  0.000000  0.324676  0.00000  ...  0.255978  0.255978  0.324676  0.000000   
1  0.000000  0.000000  0.00000  ...  0.000000  0.000000  0.000000  0.607841   
2  0.000000  0.000000  0.34604  ...  0.272822  0.272822  0.000000  0.000000   
3  0.359685  0.000000  0.00000  ...  0.000000  0.000000  0.000000  0.567160   

   processing     sport    sports     study  understand     world  
0    0.324676  0.000000  0.000000  0.255978    0.324676  0.000000  
1    0.000000  0.000000  0.385484  0.000000    0.000000  0.000000  
2    0.000000  0.000000  0.000000  0.272822    0.000000  0.000000  
3    0.000000  0.359685  0.000000  0.000000    0.000000  0.359685  

[4 rows x 25 columns]

In [23]:
documents

['Natural Language Processing is the study of making a machine understand and generate languages like humans',
 'Cricket is a sports played with a bat and a ball. It is not played in many countries',
 'Languages are the cornerstone of human evolution. Making a machine study languages is not easy',
 'Football is a sport played in almost all countries of the world. It is played by kicking a ball']

## Calculating the document similarities

* Cosine similarity is a metric used to measure how similar the documents are irrespective of their size. Mathematically, it measures the cosine of the angle between two vectors projected in a multi-dimensional space
* The cosine similarity is advantageous because even if the two similar documents are far apart by the Euclidean distance (due to the size of the document), chances are they may still be oriented closer together. The smaller the angle, higher the cosine similarity

In [24]:
from sklearn.metrics.pairwise import cosine_similarity as c_sim

In [25]:
arr = tf_matrix_docs[0].toarray()

In [28]:
arr

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.32467583, 0.        ,
        0.32467583, 0.        , 0.32467583, 0.25597815, 0.32467583,
        0.25597815, 0.25597815, 0.32467583, 0.        , 0.32467583,
        0.        , 0.        , 0.25597815, 0.32467583, 0.        ]])

In [29]:
type(arr),arr.shape

(numpy.ndarray, (1, 25))

In [30]:
c_sim(tf_matrix_docs[0],tf_matrix_docs[2])

array([[0.34918271]])

In [32]:
c_sim(tf_matrix_docs[0],tf_matrix_docs[1])

array([[0.]])

In [33]:
c_sim(tf_matrix_docs[1],tf_matrix_docs[2])

array([[0.]])

In [34]:
c_sim(tf_matrix_docs[1],tf_matrix_docs[3])

array([[0.51711443]])

In [45]:
c_sim(tf_matrix_docs[3],tf_matrix_docs[3])

array([[1.]])

In [46]:
c_sim(tf_matrix_docs[2],tf_matrix_docs[3])

array([[0.]])